filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"