filebeat.inputs:
  - type: log
    paths:
      - /var/log/api-server/*.log

output.kafka:
  enabled: true
  hosts: ["logstash:9092"]
  topic: 'api-server'

# output.logstash:
#   enabled: true
#   hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"