spring:
  datasource:
#    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3306/csv?useSSL=false&serverTimezone=Asia/Seoul
    username: test
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
#      host: ${MONGO_HOST}
#      port: ${MONGO_PORT}
#      authentication-database: admin
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: password
      database: feed


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
