spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: true
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true